### ISSUE TITLE
Bug in BMC-MuxInAnalog74HC40XX.h and problems with connecting to programmed Teensy 4.1

### ISSUE THREAD

**Issue by mateomodar** [neroroxxx/BMC#10]
When i use 74hc4051 i get this error:
[error_message.txt](https://github.com/neroroxxx/BMC/files/14539933/error_message.txt)
Also when i dont use a 74hc4051 the upload works just fine but BMC 2.2.3 seems to do nothing when i try to connect to the programmed Teensy4.1. When i try to load the button led example project i can connect just fine.

**Comment by neroroxxx** [comment]
can you attach the config.h file with the 74HC40? sorry I completely missed this one

**Comment by mateomodar** [comment]
Hey, also wasnt on the PC for some days, here is the config.h file:
[configh.txt](https://github.com/neroroxxx/BMC/files/15054608/configh.txt)

**Comment by neroroxxx** [comment]
Thank you for reporting the bug, this is fixed in version 2.2.4
