### ISSUE TITLE
Error when starting up the Midi device

### ISSUE THREAD

**Issue by mateomodar** [neroroxxx/BMC#11]
With this config file: 
[configh_new.txt](https://github.com/neroroxxx/BMC/files/15149070/configh_new.txt)
I now get this error:
[error_new.txt](https://github.com/neroroxxx/BMC/files/15149103/error_new.txt)
Seems like it selects a wrong Mux pin that is not assignable.

**Comment by neroroxxx** [comment]
What version of the library are you using?

**Comment by mateomodar** [comment]
Im using 1.59 boards manager and 2.2.4 library.

**Comment by neroroxxx** [comment]
Im doing some testing right now, can you reupload the sketch and confirm that the mux pin that's giving you the error is still 65, im getting pin 80 as the error

**Comment by neroroxxx** [comment]
Ok so i think i found the bug, if you could test it that'd be great.

in the library go to src/utility/BMC-BuildData.h and open this file in a text editor

Scroll to the very end of the file and look for this line, should be line # 7491

`if(isMuxInKeypadPinIndex(n)){return true;}`

Replace it with 

`if(isMuxInKeypadPin(n)){return true;}`

Try reuploading and check if everything is working as expected

**Comment by mateomodar** [comment]
Yes, this works out, thanks for the fast help as allways :D

**Comment by mateomodar** [comment]
Now this works, i get it uploaded and also can connect to the device but keymatrixes seem to have a bug. In the first two rows the next button (when button 1 -> button 2, when button 4 -> button 5) also reacts. They do this even when pulled down. Row 3 and 4 seem to work properly. I even changed pins to different ones, problem stays the same.

**Comment by mateomodar** [comment]
Hey neroroxxx, did you had time to look into this?

**Comment by neroroxxx** [comment]
I only have a 4x4 matrix and it seems to be working correctly, can you post this as a different issue to track it better, im going to see if i can add some debugging code to se what's going on.
