### ISSUE TITLE
Compilation Error on basic sketch

### ISSUE THREAD

**Issue by Knoplund** [neroroxxx/BMC#5]
Hi,

First, Thank you for your great work. I used BMC before to successfully build a Controler, about a year ago. I now wanted to build a different one, but I can't even get the basic "first BMC sketch" to compile.
I use: 
Arduino IDE 2.0.4
Teensy Boards 1.58.0
Latest BMC Library (1.7.2.)
BMC Boards 1.0.0
I tried using Teensy 3.6 and Teensy 4.0

Followed the new instructions for Arduino IDE 2X
I tested it on two different Windows 10 Machines, one of which was a fresh Installation. I allready deinstalled all arduino IDE, libraries and so on, and installed it all anew, but no luck.

Errorlog attatched, Thank you in advance

[BMCCompileErrorLog.txt](https://github.com/neroroxxx/BMC/files/11266197/BMCCompileErrorLog.txt)

**Comment by neroroxxx** [comment]
Hi, downgrade teensyduino to 1.57.2, 1.58 has a new toolchain and there's a lot of changes that need to be made to BMC, I already did these changes for BMC 2.0 but i haven't had the time to update the current release

**Comment by neroroxxx** [comment]
BMC version 1.7.3 now supports Teensyduino 1.58

**Comment by mateomodar** [comment]
Sure 

[config_h.txt](https://github.com/neroroxxx/BMC/files/14511675/config_h.txt)
