### ISSUE TITLE
Error compiling for board Teensy 4.1 (BMC).

### ISSUE THREAD

**Issue by ghost** [neroroxxx/BMC#6]
C:\Users\*****\Documents\Arduino\libraries\BMC-2.2.1\src/editor/onBoard/BMC-OBEMain.h:153:12: error: 'ret' was not declared in this scope

**Comment by neroroxxx** [comment]
Can you share your config.h file and let m eknow what version of BMC you're using

**Comment by neroroxxx** [comment]
Version 2.2.2 has this resolved

**Comment by ghost** [comment]
Version 2.2.2 work ok.
