### ISSUE TITLE
Keypad Option in Config File Maker not working properly

### ISSUE THREAD

**Issue by mateomodar** [neroroxxx/BMC#7]
The Keypad Option in the Config File Maker not working properly. Every time i insert a number of rows and columns over 4 or sometimes 5 (its inconsistent) it says too many pins used in the hardware options afterwards. When i get back it says for example 5 rows x 4 columns instead of the before selected 8 rows x 5 columns. Thanks for any help in advance, i know this is a new feature!

**Comment by neroroxxx** [comment]
Hi, can you get a screenshot of the error message? i see the bug that shows the wrong number of keys which i can fix.

**Comment by mateomodar** [comment]
![Screenshot 2024-03-05 155253](https://github.com/neroroxxx/BMC/assets/162223454/c23d3dda-f47f-4c3b-8ea3-77e7d4ad0535)
This is how i configerated the rows and columns
![Screenshot 2024-03-05 155413](https://github.com/neroroxxx/BMC/assets/162223454/50629a4f-2802-4741-ae8d-a14397a17af2)
This is how the error message then looks, 40 keys are selected. In global there is just one button and one encouder, shouldnt be too much pins.  The 16 pot inputs are with a multiplexer. 
![Screenshot 2024-03-05 155440](https://github.com/neroroxxx/BMC/assets/162223454/f2be1570-a06d-4a37-aed0-cece9e2e5b7c)
When i go back to previous page it says in this case 8 rows x 4 columns, even tho 8x5 where selected before. Thanks for the fast reply!

**Comment by neroroxxx** [comment]
Thank you for the info, all fixed on editor version 2.2.1

**Comment by neroroxxx** [comment]
Thank you for the info, all fixed on editor version 2.2.1, should automatically update on the browser just make you are running version 2.2.1
